server:
  port: 8000
ui:
  enabled: true
  name: Shraga
  title: Shraga
  default_flow: default
  list_flows: true
  loading_messages:
  - Looking up relevant information
  - Compiling analysis and sources
  - Generating answer
retrievers:
  opensearch:
    type: opensearch
    host: ${OPENSEARCH_HOST}
    index: ${OPENSEARCH_INDEX}
    port: ${OPENSEARCH_PORT}
    use_ssl: ${OPENSEARCH_USE_SSL}
    verify_certs: ${OPENSEARCH_VERIFY_CERTS}
    auth_method: ${OPENSEARCH_AUTH_METHOD}
    user: ${OPENSEARCH_USER}
    password: ${OPENSEARCH_PASSWORD}
  elasticsearch:
    type: elasticsearch
    use_cloud_id: ${ELASTICSEARCH_USE_CLOUD_ID}
    cloud_id: ${ELASTICSEARCH_CLOUD_ID}
    host: ${ELASTICSEARCH_HOST}
    port: ${ELASTICSEARCH_PORT}
    use_ssl: ${ELASTICSEARCH_USE_SSL}
    verify_certs: ${ELASTICSEARCH_VERIFY_CERTS}
    auth_type: ${ELASTICSEARCH_AUTH_TYPE}
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PASSWORD}
    api_key: ${ELASTICSEARCH_API_KEY}
    index: ${ELASTICSEARCH_INDEX}
services:
  openai:
    api_key: ${OPENAI_API_KEY}
  googlemaps:
    api_key: ${GOOGLE_MAPS_KEY}
    dark_map_id: ${GOOGLE_MAPS_DARK_MAP_ID}
    light_map_id: ${GOOGLE_MAPS_LIGHT_MAP_ID}
auth:
  session_timeout: 24
  users:
  - user@domain.com
  realms:
    basic:
    - user@domain.com:secretpwd
    jwt:
      secret: foobar
    google:
      client_id: ${GOOGLE_CLIENT_ID}
      client_secret: ${GOOGLE_CLIENT_SECRET}
    microsoft:
      client_id: ${MICROSOFT_CLIENT_ID}
      client_secret: ${MICROSOFT_CLIENT_SECRET}
aws:
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  assets_bucket: mybucket
history:
  enabled: true
  index: chat-history
  analytics:
    domains:
    - bigdataboutique.com
flows:
  input_max_length: 1000
