server:
  port: 8000
ui:
  enabled: true
  name: Shraga
  title: Shraga
  default_flow: demo
  list_flows: true
  loading_messages:
  - Looking up relevant information
  - Compiling analysis and sources
  - Generating answer
retrievers:
  elasticsearch:
    type: elasticsearch
    use_cloud_id: ${ELASTICSEARCH_USE_CLOUD_ID}
    cloud_id: ${ELASTICSEARCH_CLOUD_ID}
    host: ${ELASTICSEARCH_HOST}
    port: ${ELASTICSEARCH_PORT}
    use_ssl: ${ELASTICSEARCH_USE_SSL}
    verify_certs: ${ELASTICSEARCH_VERIFY_CERTS}
    auth_type: ${ELASTICSEARCH_AUTH_TYPE}
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PASSWORD}
    api_key: ${ELASTICSEARCH_API_KEY}
    index: ${ELASTICSEARCH_INDEX}
auth:
  users:
  - user@domain.com
  realms:
    basic:
    - user@domain.com:$2b$12$brwB79JExWprqHPEm4P76uuBsH0Cht8PFiBePKtHnl5g/cibYXpDu
    jwt:
      secret: foobar
    google:
      client_id: ${GOOGLE_CLIENT_ID}
      client_secret: ${GOOGLE_CLIENT_SECRET}
    microsoft:
      client_id: ${MICROSOFT_CLIENT_ID}
      client_secret: ${MICROSOFT_CLIENT_SECRET}
history:
  enabled: false
  analytics:
    users:
    - user@domain.com
    domains:
    - bigdataboutique.com
evaluation:
  index: eval-index-name
